# Calculating with NumPy Arrays

In [1]:
revenue = [112545.11,402753.54,525574.84,875442.86]
costs = [149252.49,301241.69,442827.37,657854.26]

import numpy as np
revenue = np.array(revenue)
costs = np.array(costs)

profit = revenue-costs
profit

array([-36707.38, 101511.85,  82747.47, 217588.6 ])

In [2]:
investments = [100,200]
growth = [10,20]

investments = np.array(investments)
growth = np.array(growth)

investments+growth

array([110, 220])

In [3]:
np.mean(profit)

91285.13499999998

In [4]:
np.std(profit)

90155.59687337067

In [5]:
profit[2]

82747.46999999997

In [6]:
profit[profit>0]

array([101511.85,  82747.47, 217588.6 ])

# Multidimensional NumPy Arrays

In [7]:
revenue = [112545.11,402753.54,525574.84,875442.86]
costs = [149252.49,301241.69,442827.37,657854.26]

import numpy as np
revenue = np.array(revenue)
costs = np.array(costs)

In [8]:
q_sales = np.array([revenue,
                   costs])
q_sales

array([[112545.11, 402753.54, 525574.84, 875442.86],
       [149252.49, 301241.69, 442827.37, 657854.26]])

In [9]:
q_sales.shape

(2, 4)

In [10]:
q_sales[0][3]

875442.86

In [11]:
q_sales[0,3]

875442.86

In [12]:
q_sales[:,1:3]

array([[402753.54, 525574.84],
       [301241.69, 442827.37]])